### ISSUE TITLE
The option "continueUrl" does not exist.

### ISSUE THREAD

**Issue by grexlort** [piotrantosik/AntQaPayUBundle#4]
I copied the example from the documentation and this does not work. Maybe it's a mistake in the documentation.

Error:
The option "continueUrl" does not exist. Known options are: "buyer", "completeUrl", "currencyCode", "customerIp", "description", "extOrderId", "merchantPosId", "notifyUrl", "products", "totalAmount".

BTW, Is continueUrl equal to completeUrl?

**Comment by piotrantosik** [comment]
Hi!

Thanks for using bundle & reporting issue!

completeUrl replaced with continueUrl in openpayu 2.1 - bug has been fixed
